[TASK] Align with new TYPO3 documentation standards
FriendsOfTYPO3/compatibility6 pull request #24
Opened 2022-04-02 06:59 UTC by alexander-nitsche

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

2022-04-08 13:45 UTC, alexander-nitsche commented
Added two new commits regarding badges in README and additional sources (TER and repository) in composer.json.

In addition, the TER homepage is missing the "Packagist" button, which seem to be caused by an empty "Composer name of extension" field in the TER extension edit form.

Relates: TYPO3-Documentation/T3DocTeam#185

2022-04-20 12:40 UTC, ohader requested changes
Target was TYPO3 v7, not v11

2022-04-20 12:40 UTC, ohader commented on README.md
> +[![TYPO3 11](https://img.shields.io/badge/TYPO3-7-orange.svg?style=flat-square)](https://get.typo3.org/version/7)
v11??

2022-04-21 09:05 UTC, alexander-nitsche commented on README.md
> +[![TYPO3 11](https://img.shields.io/badge/TYPO3-7-orange.svg?style=flat-square)](https://get.typo3.org/version/7)
Lost in batch processing. Done.

2022-04-21 09:17 UTC, ohader approved these changes

2022-04-21 09:18 UTC, merged

2022-04-21 09:19 UTC, ohader commented
packagist.org reference added in TER